name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Roda todos os dias Ã  meia-noite UTC
  push:
    branches:
      - main # ou 'master', dependendo do nome da sua branch principal

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Snake Animation ğŸ

    steps:
      - name: ğŸ“¥ Checkout do repositÃ³rio
        uses: actions/checkout@v3

      - name: ğŸ Gerando animaÃ§Ã£o Snake
        uses: Platane/snk@v3
        with:
          github_user_name: alt-jvictor
          outputs: |
            dist/snake.svg

      - name: ğŸ’¾ Commit e push do SVG
        uses: EndBug/add-and-commit@v9
        with:
          message: "ğŸŒ€ AtualizaÃ§Ã£o da animaÃ§Ã£o Snake"
          add: "dist/snake.svg"
